### PR TITLE
Updated tickets message on Home page

### PR DESCRIPTION
**Pull request by soachishti**
Hi @murad-hubib , Please review and accept the PR.

### CODE REVIEW

**Comment by soachishti** [comment]
Hi @murad-hubib , any update on this?

**Review by murad-hubib — APPROVED** [review]
@soachishti do you have merge rights or you need me to merge it?

**Comment by soachishti** [comment]
Yes, I don't have merge rights.

**Comment by murad-hubib** [comment]
@soachishti I have merged the PR

**Comment by soachishti** [comment]
Thanks!

**Comment by soachishti** [comment]
It seems like updated code isn't deployed yet. The website is still showing old changes. @murad-hubib Can you please look into this.

**Pull request merged**
