### PR TITLE
Added Dynamic Sponsors, Speakers And Gallery

### PR DESCRIPTION
**Pull request by hamza-jutt**
Added Dynamic Sponsors on Home Page
Added Dynamic Gallery on Home Page
Added Speakers and sponsors page
Added gallery listing and gallery detail page
Fixed footer links, removed phone from roof

### CODE REVIEW

**Comment by ybashir** [comment]
Should have noticed while merging but I dont think these content types belong in the theme app. They should go to the main pycon app.  The theme app is just for the look and feel.

**Comment by hamza-jutt** [comment]
Well you are right about that. but main pycon_web is not a django app it is rather a project. Content types should not be in a theme but I think there should not be a app named theme. @ybashir

**Comment by ybashir** [comment]
Right, what i was suggesting was that perhaps we need to create another app called **main**. 

We created the **theme** app to make it reusable (so simply drag and drop that package in another mezzanine project and get the same theme there) but you are right, the theme itself is now heavily reliant on the new content types so may not work. What refactoring would you suggest based on Mezz documentatoin?

**Comment by hamza-jutt** [comment]
Mezzanine has nothing to do with it. The project structure comes from django. which clearly states that every app should be unit that is not dependent on other apps hence reusable. it should contains related views, urls, templates, models.
So here I believe we should refactor app name. that would be sufficient for this size of a project. If it were  bigger we could create app for gallery, blog that would contain relevant templates, views etc.

**Comment by ybashir** [comment]
Makes sense. Lets rename it to something more meaningful then. What app name do you suggest?

**Comment by hamza-jutt** [comment]
well it isn't a specific app it contains all the project almost, so might rename it to `main`.

**Pull request merged**
