### PR TITLE
Updated PyCon year in settings.py

### PR DESCRIPTION
**Pull request by soachishti**
@murad-hubib Please accept, merge and deploy.

### CODE REVIEW

**Comment by soachishti** [comment]
@murad-hubib any update?

**Review by murad-hubib — APPROVED** [review]

**Comment by murad-hubib** [comment]
> @murad-hubib any update?

@soachishti Deployed! Please always leave a message on RC so I can schedule it

**Comment by soachishti** [comment]
> > @murad-hubib any update?
> 
> @soachishti Deployed! Please always leave a message on RC so I can schedule it

@murad-hubib What is RC? Relay Chat?

**Comment by murad-hubib** [comment]
> > > @murad-hubib any update?
> > 
> > 
> > @soachishti Deployed! Please always leave a message on RC so I can schedule it
> 
> @murad-hubib What is RC? Relay Chat?

Rocket Chat

**Pull request merged**
