### PR TITLE
Changes for PyCon'19

### PR DESCRIPTION
**Pull request by soachishti**
CC: @waqasahmad12345

### CODE REVIEW

**Comment by murad-hubib** [comment]
@soachishti do you want me to review this PR?

**Comment by soachishti** [comment]
@murad-hubib Yes. We are organizing PyCon'19 and need to update site for this year. We have admin panel details from Waqas already, but some changes cannot be made from the panel. Please review (and deploy) this PR.

**Review by murad-hubib — APPROVED** [review]

**Comment by murad-hubib** [comment]
@soachishti  Done

**Comment by murad-hubib** [comment]
@soachishti Never mind, please always create a branch from your fork:master

**Comment by murad-hubib** [comment]
@soachishti Deployed. Please verify

**Comment by soachishti** [comment]
Thanks for merging, it is up and working.

**Pull request merged**
